version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - milvus
      - labelstudio

  milvus:
    image: milvusdb/milvus:latest
    ports:
      - "19530:19530"
      - "19121:19121"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530

  labelstudio:
    image: heartexlabs/label-studio:latest
    ports:
      - "8080:8080"
    volumes:
      - label_studio_data:/label-studio/data
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true

volumes:
  milvus_data:
  label_studio_data: 